name: smartm
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  email_validator: ^3.0.0
  flutter:
    sdk: flutter
  flutter_map: ^6.1.0
  fluttericon: ^2.0.0
  http: 1.1.0
  latlong2: ^0.9.1
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/LogoHorizontal.png
http: ^0.13.4
flutter_map: ^0.13.1